apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/okuda-seminar/Twitter-Clone.git
    targetRevision: main
    path: kustomize/overlays/stg

