apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: rollout-blue-green
kind: Kustomization
metadata:
  namespace: default
resources:
  - deployment.yaml
  - service-active.yaml
  - service-preview.yaml

  # Version 2023-03-01-1677634140
openapi:
  path: https://github.com/argoproj/argo-schema-generator/raw/2023-03-01-1677634140/schema/argo_all_k8s_kustomize_schema.json


